current_pose_to_car_front: 4.0  # m
braking_reaction_time: 1.6      # s
stopping_lateral_distance: 1.35 # m
slowdown_lateral_distance: 1.60 # m
waypoint_interval: 1.0          # m
default_acceleration: 1.0       # m/s2
default_deceleration: 1.0       # m/s2
max_deceleration: 10.0          # m/s2
stopping_speed_limit: 1.0       # m/s
lane_change_base_length: 10.0   # m
lane_change_perlane_length: 5.0 # m
speed_limit: 50.0               # max velocity for route (km/h), will be replaced by speed taken from map
output_frame: map
distance_to_goal_limit: 5.0     # m
ego_vehicle_stopped_speed_limit: 0.1

lanelet2_global_planner:
  distance_to_centerline_limit: 5.0
  lane_change: False
  lanelet_search_radius: 0.5

waypoint_loader:
  output_frame: map
  wp_left_width: 1.4
  wp_right_width: 1.4

waypoint_saver:
  interval: 1.0

path_smoothing:
  adjust_speeds_in_curves: True
  adjust_speeds_using_deceleration: True
  speed_averaging_window: 21              # window size (will be applied only if > 1)
  adjust_endpoint_speed_to_zero: True
  radius_calc_neighbour_index: 8          # int
  lateral_acceleration_limit: 1.5         # m/s2
  output_debug_info: False

local_path_extractor:
  publish_rate: 10                        # Hz 
  local_path_length: 100                  # m
goal_stop_checker:
  braking_safety_distance_goal: 0.1       # m
traffic_light_stopline_checker:
  braking_safety_distance_stopline: 2     # m
  tfl_force_stop_speed_limit: 5.0         # km/h
  tfl_maximum_deceleration: 2.8           # m/s2
local_path_collision_checker:
  braking_safety_distance_obstacle: 4     # m
pedestrian_crosswalk_checker:
  braking_safety_distance_crosswalk: 6    # m
  crossing_angle_max_limit: 70            # degrees
